### ISSUE TITLE
Syntax highlighting in .tsx files

### ISSUE THREAD

**Issue by w00ing** [11bit/zed-extension-graphql#3]
First of all, thank you for the implementation of the extension.

I'm using react-relay, so my graphql requests are mostly defined in the components themselves.
I can't get graphql highlighted properly in `.tsx` files (as well as in other file types).

`.graphql` file, highlighted properly:
<img width="746" alt="Screenshot 2024-05-09 at 13 49 40" src="https://github.com/11bit/zed-extension-graphql/assets/29723695/87b93537-0345-409b-a60f-e5d27516efd7">

`.tsx` file, not highlighted:
<img width="807" alt="Screenshot 2024-05-09 at 13 48 06" src="https://github.com/11bit/zed-extension-graphql/assets/29723695/20cf114b-78ed-422b-9e50-2f503616e926">

Would absolutely love if the extension can work for graphql syntax across different file types.

**Comment by 11bit** [comment]
Thanks!

Last time I checked, there was a problem with highlighting across different file types. In order to do that you have to modify syntax files of that file type which is not an option for an extension. So we are waiting before Zed supports overriding other grammars. ([more details, and workaround here](https://github.com/zed-industries/extensions/issues/149#issuecomment-1975667586)).

**Comment by w00ing** [comment]
Thanks for the explanation! I guess I'll have no choice but wait for Zed team to deal with this :)

**Comment by affanshahid** [comment]
This should be available with https://github.com/zed-industries/zed/pull/16368
